import type { Clue } from "../types/game";

export const clues: Clue[] = [
  {
    id: 1,
    location: "Pista Comodín",
    hint: "La esfinge te pregunta: '¿Quién en esta fiesta ha estudiado como defender a la justicia, siempre con elegancia?' Esta persona tiene el papel que necesitas. Debes encontrarla y pedirle la respuesta secreta.",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "special",
    answer: "tia_abogada",
  },
  {
    id: 2,
    location: "Dormitorio",
    hint: "Abajo del vaporizador.",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "code",
    answer: "dream_sequence_42",
  },
  {
    id: 3,
    location: "Baño",
    hint: "Donde el agua y el misterio se esconden tras puertas de madera",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "special",
    answer: "steam_mirror_truth",
  },
  {
    id: 4,
    location: "Patio",
    hint: "Donde crecen las ideas verdes y la tierra guarda secretos",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "special",
    answer: "green_thumb_secret",
  },
  {
    id: 5,
    location: "Cocina",
    hint: "Donde el calor transforma y el secreto se esconde bajo el fuego",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "special",
    answer: "flame_override_777",
  },
  {
    id: 6,
    location: "Escritorio",
    hint: "Donde la creatividad descansa entre colores y papeles",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "special",
    answer: "creative_mind_2024",
  },
  {
    id: 7,
    location: "Living",
    hint: "Donde las bebidas se reúnen y la tecnología se esconde entre ellas",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "special",
    answer: "cocktail_hack_1337",
  },
  {
    id: 8,
    location: "Living",
    hint: "Donde el descanso es rey y los secretos se ocultan bajo los cojines",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "special",
    answer: "comfort_zone_alpha",
  },
  {
    id: 9,
    location: "Garage",
    hint: "En el garage, en la mesa de carpintería.",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "code",
    answer: "shadow_garage_999",
  },
  {
    id: 10,
    location: "Ropero",
    hint: "En la parte de arriba, donde las prendas descansan y los secretos se ocultan",
    difficulty: "legendary",
    hackRequired: true,
    hackType: "special",
    answer: "wardrobe_treasure_final",
  },
];
